### ISSUE TITLE
current json does not contain STM32 BSP

### ISSUE THREAD

**Issue by christianpaetz** [RAKWireless/RAKwireless-Arduino-BSP-Index#4]
Hi,the https://raw.githubusercontent.com/RAKwireless/RAKwireless-Arduino-BSP-Index/main/package_rakwireless.com_rui_index.json as shown in readme does not have the STM32 as shown in the readme.

**Comment by beegee-tokyo** [comment]
We are still fixing some bugs and compatibility problems with Arduino libraries. Should be out in the next week.
