### ISSUE TITLE
Incorrect file size for `buildtime` tool

### ISSUE THREAD

**Issue by rcoder** [RAKWireless/RAKwireless-Arduino-BSP-Index#5]
When installing the RUI platform via `arduino-cli` I get the following error:

```
arduino-cli core install $BOARD_CORE
Downloading packages...
rak_rui:arm-none-eabi-gcc@9-2019q4 already downloaded
rak_rui:nrfjprog@10.15.4 already downloaded
rak_rui:uploader@0.0.0 already downloaded
rak_rui:pc-nrfutil@v6.1.3 already downloaded
rak_rui:buildtime@v0.0.0 downloaded                                                                                                                    
rak_rui:nrf52@3.4.2 already downloaded
Installing rak_rui:arm-none-eabi-gcc@9-2019q4...
rak_rui:arm-none-eabi-gcc@9-2019q4 installed
Installing rak_rui:nrfjprog@10.15.4...
rak_rui:nrfjprog@10.15.4 installed
Installing rak_rui:uploader@0.0.0...
rak_rui:uploader@0.0.0 installed
Installing rak_rui:pc-nrfutil@v6.1.3...
rak_rui:pc-nrfutil@v6.1.3 installed
Installing rak_rui:buildtime@v0.0.0...
Error during install: installing tool rak_rui:buildtime@v0.0.0: testing local archive integrity: testing archive size: fetched archive size differs from size specified in index
```

When I manually downloaded the tool from the URL[^1] in the library manifest[^2] the MD5 checksum matched but the size did not (410 bytes vs. 446). I also checked and both the MacOS and Win32 downloads of the `buildtime` tool appear to have incorrect file sizes as well.

I'm not sure what the upstream packaging process looks like for these tools, and whether this JSON listing is updated automatically or by hand, but at minimum it seems like the file sizes listed in the JSON need to be updated.

In the meantime I can manually patch the JSON locally but obviously that will fall behind as any other changes are made upstream.

[^1]: https://downloads.rakwireless.com/RUI/RUI3/Tools/buildtime-linux.tar.gz
[^2]: https://github.com/RAKWireless/RAKwireless-Arduino-BSP-Index/blob/main/package_rakwireless.com_rui_index.json#L457

**Comment by beegee-tokyo** [comment]
Hi @rcoder 
I just did a fresh install of both RUI3 nRF52 and STM32 BSP's and it worked without problems.

Could be that Arduino had something in its cache or staging folder. Our R&D guy who is maintaining this repo is looking into it.

**Comment by rcoder** [comment]
Thanks for the follow-up. I'm a little surprised that the file sizes listed in the manifest aren't causing problems since I checked both the current index JSON from this repo and the download packages explicitly referenced in it, but then again I'm specifically using the `arduino-cli` toolchain, which may be changing the package caching/path resolution/etc. behavior...not to mention having Nix manage my environment.

All of the above may introduce one (or N, really) too many variables for y'all to track down a root cause. I'm starting to think that I should just drop the `arduino-cli` experiment and go for `pio` everywhere, but it was a nice idea at least to be able to drop arbitrary Arduino projects into my headless build setup...

**Comment by beegee-tokyo** [comment]
The team is still looking into it. It installs without errors on ArduinoIDE and Visual Studio Code.

We are not supporting PIO (yet), but you can use VSC together with the Arduino extension.

Here is a short guide
[RUI3 on Visual Studio Code.pdf](https://github.com/RAKWireless/RAKwireless-Arduino-BSP-Index/files/8790289/RUI3.on.Visual.Studio.Code.pdf)

**Comment by beegee-tokyo** [comment]
Hi @rcoder 

The problem is fixed. It should now install as expected with Arduino CLI.
Commit https://github.com/RAKWireless/RAKwireless-Arduino-BSP-Index/commit/0a8308e39fb59445f2d4c7db9c268f44f8df40fe
